### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by xinyihl** [Xiaoxianben/LazyMystical#1]
https://github.com/Xiaoxianben/LazyMystical/blob/dccaef8c46fa73099ded3cb02a9f5aa9f933efd2/src/main/java/com/xiaoxianben/lazymystical/event/ConfigLoader.java#L3
这个包只能在物理客户端上使用。但是你这个class在物理服务端也会加载。
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Lazy Mystical (lazymystical)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
    at com.xiaoxianben.lazymystical.event.ConfigLoader.addInt(ConfigLoader.java:43)
    at com.xiaoxianben.lazymystical.event.ConfigLoader.addInt(ConfigLoader.java:39)
    at com.xiaoxianben.lazymystical.event.ConfigLoader.load(ConfigLoader.java:77)
    at com.xiaoxianben.lazymystical.event.ConfigLoader.preInitConfigLoader(ConfigLoader.java:35)
    at com.xiaoxianben.lazymystical.Main.preInit(Main.java:52)
    at ....(以下省略)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 40 more
Caused by: java.lang.NullPointerException
```

**Comment by Xiaoxianben** [comment]
@xinyihl v1.2.0 已修复，可以去试试。抱歉拖得有点久，因为我正在写另一个模组。
